# Play varibles level

- name: varibles from Play level
  hosts: localhost
  vars:
    Course: "Ansible"
    Trainer: "Pavan"
    Duration: "8HRS"
  tasks:
  - name: cheeck variables 
    ansible.builtin.debug:
     msg: "Hi, i am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}},"  